name: TidesDB C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tidesdb-cpp repo
      uses: actions/checkout@v4
      with:
        repository: tidesdb/tidesdb-cpp
        path: tidesdb-cpp

    - name: Checkout tidesdb repo
      uses: actions/checkout@v4
      with:
        repository: tidesdb/tidesdb
        path: tidesdb

    - name: Install libzstd-dev,liblz4-dev and libsnappy-dev
      run: |
        sudo apt update
        sudo apt install -y libzstd-dev liblz4-dev libsnappy-dev

    - name: configure cmake build for tidesdb
      run: |
        cd tidesdb
        cmake -DTIDESDB_WITH_SANITIZER=OFF --debug-output  -S . -B build && make -C build/
        sudo cmake --install build

    - name: configure cmake build
      run: |
        cd tidesdb-cpp
        cmake --debug-output  -S . -B build && make -C build/

    - name: run tests
      run: |
        cd tidesdb-cpp/build
        ctest --output-on-failure

